# Generated by Django 4.1.7 on 2023-04-01 11:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='availableservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableservices_title', models.CharField(max_length=50, null=True)),
                ('availableservices_desc', ckeditor.fields.RichTextField()),
                ('availableservices_tags', ckeditor.fields.RichTextField()),
                ('availableservices_url', models.URLField(null=True)),
            ],
        ),
    ]
