# Generated by Django 4.1.7 on 2023-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0002_availableservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableservices',
            name='availableservices_subtitile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
