# Generated by Django 4.1.7 on 2023-04-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0004_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableservices',
            name='availableservices_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
