# Generated by Django 4.1.7 on 2023-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0005_alter_availableservices_availableservices_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_img', models.ImageField(upload_to='media')),
                ('member_designation', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
