# Generated by Django 4.1.7 on 2023-04-03 05:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0006_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_number',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='member_name', unique=True),
        ),
    ]
