# Generated by Django 4.1.7 on 2023-04-03 16:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0007_team_member_number_team_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableservices',
            name='availableservices_url',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.CharField(max_length=50, null=True), unique=True),
        ),
    ]
