# Generated by Django 4.1.7 on 2023-04-03 16:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnotion', '0008_alter_availableservices_availableservices_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableservices',
            name='availableservices_desc_add',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
